apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flannel-operator
  labels:
    operator: flannel
spec:
  replicas: 1
  template:
    metadata:
      labels:
        operator: flannel
    spec:
      containers:
        - name: flannel-operator
          image: stephenking/flannel-operator:0.1.5 # 0.1.4 is with flannel 0.7.0
